using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace InventoryManagement.Models
{
    public class MimeTypeMap
    {
        private static readonly Lazy<IDictionary<string, string>> _mappings = new Lazy<IDictionary<string, string>>(BuildMappings);

        private static IDictionary<string, string> BuildMappings()
        {
            var mappings = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase) {

                #region Big freaking list of mime types
            
                // maps both ways,
                // extension -> mime type
                //   and
                // mime type -> extension
                //
                // any mime types on left side not pre-loaded on right side, are added automatically
                // some mime types can map to multiple extensions, so to get a deterministic mapping,
                // add those to the dictionary specifcially
                //
                // combination of values from Windows 7 Registry and 
                // from C:\Windows\System32\inetsrv\config\applicationHost.config
                // some added, including .7z and .dat
                //
                // Some added based on http://www.iana.org/assignments/media-types/media-types.xhtml
                // which lists mime types, but not extensions
                //
                {".323", "text/h323"},
                {".3g2", "video/3gpp2"},
                {".3gp", "video/3gpp"},
                {".3gp2", "video/3gpp2"},
                {".3gpp", "video/3gpp"},
                {".7z", "application/x-7z-compressed"},
                {".aa", "audio/audible"},
                {".AAC", "audio/aac"},
                {".aaf", "application/octet-stream"},
                {".aax", "audio/vnd.audible.aax"},
                {".ac3", "audio/ac3"},
                {".aca", "application/octet-stream"},
                {".accda", "application/msaccess.addin"},
                {".accdb", "application/msaccess"},
                {".accdc", "application/msaccess.cab"},
                {".accde", "application/msaccess"},
                {".accdr", "application/msaccess.runtime"},
                {".accdt", "application/msaccess"},
                {".accdw", "application/msaccess.webapplication"},
                {".accft", "application/msaccess.ftemplate"},
                {".acx", "application/internet-property-stream"},
                {".AddIn", "text/xml"},
                {".ade", "application/msaccess"},
                {".adobebridge", "application/x-bridge-url"},
                {".adp", "application/msaccess"},
                {".ADT", "audio/vnd.dlna.adts"},
                {".ADTS", "audio/aac"},
                {".afm", "application/octet-stream"},
                {".ai", "application/postscript"},
                {".aif", "audio/aiff"},
                {".aifc", "audio/aiff"},
                {".aiff", "audio/aiff"},
                {".air", "application/vnd.adobe.air-application-installer-package+zip"},
                {".amc", "application/mpeg"},
                {".anx", "application/annodex"},
                {".apk", "application/vnd.android.package-archive" },
                {".application", "application/x-ms-application"},
                {".art", "image/x-jg"},
                {".asa", "application/xml"},
                {".asax", "application/xml"},
                {".ascx", "application/xml"},
                {".asd", "application/octet-stream"},
                {".asf", "video/x-ms-asf"},
                {".ashx", "application/xml"},
                {".asi", "application/octet-stream"},
                {".asm", "text/plain"},
                {".asmx", "application/xml"},
                {".asp", "asp/File"},
                {".aspx", "application/xml"},
                {".asr", "video/x-ms-asf"},
                {".asx", "video/x-ms-asf"},
                {".atom", "application/atom+xml"},
                {".au", "audio/basic"},
                {".avi", "video/x-msvideo"},
                {".axa", "audio/annodex"},
                {".axs", "application/olescript"},
                {".axv", "video/annodex"},
                {".bas", "text/plain"},
                {".bcpio", "application/x-bcpio"},
                {".bin", "application/octet-stream"},
                {".bmp", "image/bmp"},
                {".c", "text/plain"},
                {".cab", "application/octet-stream"},
                {".caf", "audio/x-caf"},
                {".calx", "application/vnd.ms-office.calx"},
                {".cat", "application/vnd.ms-pki.seccat"},
                {".cc", "text/plain"},
                {".cd", "text/plain"},
                {".cdda", "audio/aiff"},
                {".cdf", "application/x-cdf"},
                {".cer", "application/x-x509-ca-cert"},
                {".cfg", "text/plain"},
                {".chm", "application/octet-stream"},
                {".class", "application/x-java-applet"},
                {".clp", "application/x-msclip"},
                {".cmd", "text/plain"},
                {".cmx", "image/x-cmx"},
                {".cnf", "text/plain"},
                {".cod", "image/cis-cod"},
                {".config", "application/xml"},
                {".contact", "text/x-ms-contact"},
                {".coverage", "application/xml"},
                {".cpio", "application/x-cpio"},
                {".cpp", "text/plain"},
                {".crd", "application/x-mscardfile"},
                {".crl", "application/pkix-crl"},
                {".crt", "application/x-x509-ca-cert"},
                {".cs", "text/plain"},
                {".csdproj", "text/plain"},
                {".csh", "application/x-csh"},
                {".csproj", "text/plain"},
                {".css", "text/css"},
                {".csv", "text/csv"},
                {".cur", "application/octet-stream"},
                {".cxx", "text/plain"},
                {".dat", "application/octet-stream"},
                {".datasource", "application/xml"},
                {".dbproj", "text/plain"},
                {".dcr", "application/x-director"},
                {".def", "text/plain"},
                {".deploy", "application/octet-stream"},
                {".der", "application/x-x509-ca-cert"},
                {".dgml", "application/xml"},
                {".dib", "image/bmp"},
                {".dif", "video/x-dv"},
                {".dir", "application/x-director"},
                {".disco", "text/xml"},
                {".divx", "video/divx"},
                {".dll", "application/x-msdownload"},
                {".dll.config", "text/xml"},
                {".dlm", "text/dlm"},
                {".doc", "application/msword"},
                {".docm", "application/vnd.ms-word.document.macroEnabled.12"},
                {".docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"},
                {".dot", "application/msword"},
                {".dotm", "application/vnd.ms-word.template.macroEnabled.12"},
                {".dotx", "application/vnd.openxmlformats-officedocument.wordprocessingml.template"},
                {".dsp", "application/octet-stream"},
                {".dsw", "text/plain"},
                {".dtd", "text/xml"},
                {".dtsConfig", "text/xml"},
                {".dv", "video/x-dv"},
                {".dvi", "application/x-dvi"},
                {".dwf", "drawing/x-dwf"},
                {".dwp", "application/octet-stream"},
                {".dxr", "application/x-director"},
                {".eml", "message/rfc822"},
                {".emz", "application/octet-stream"},
                {".eot", "application/vnd.ms-fontobject"},
                {".eps", "application/postscript"},
                {".etl", "application/etl"},
                {".etx", "text/x-setext"},
                {".evy", "application/envoy"},
                {".exe", "application/octet-stream"},
                {".exe.config", "text/xml"},
                {".fdf", "application/vnd.fdf"},
                {".fif", "application/fractals"},
                {".filters", "application/xml"},
                {".fla", "application/octet-stream"},
                {".flac", "audio/flac"},
                {".flr", "x-world/x-vrml"},
                {".flv", "video/x-flv"},
                {".fsscript", "application/fsharp-script"},
                {".fsx", "application/fsharp-script"},
                {".generictest", "application/xml"},
                {".gif", "image/gif"},
                {".gpx", "application/gpx+xml"},
                {".group", "text/x-ms-group"},
                {".gsm", "audio/x-gsm"},
                {".gtar", "application/x-gtar"},
                {".gz", "application/x-gzip"},
                {".h", "text/plain"},
                {".hdf", "application/x-hdf"},
                {".hdml", "text/x-hdml"},
                {".hhc", "application/x-oleobject"},
                {".hhk", "application/octet-stream"},
                {".hhp", "application/octet-stream"},
                {".hlp", "application/winhlp"},
                {".hpp", "text/plain"},
                {".hqx", "application/mac-binhex40"},
                {".hta", "application/hta"},
                {".htc", "text/x-component"},
                {".htm", "text/html"},
                {".html", "text/html"},
                {".htt", "text/webviewhtml"},
                {".hxa", "application/xml"},
                {".hxc", "application/xml"},
                {".hxd", "application/octet-stream"},
                {".hxe", "application/xml"},
                {".hxf", "application/xml"},
                {".hxh", "application/octet-stream"},
                {".hxi", "application/octet-stream"},
                {".hxk", "application/xml"},
                {".hxq", "application/octet-stream"},
                {".hxr", "application/octet-stream"},
                {".hxs", "application/octet-stream"},
                {".hxt", "text/html"},
                {".hxv", "application/xml"},
                {".hxw", "application/octet-stream"},
                {".hxx", "text/plain"},
                {".i", "text/plain"},
                {".ico", "image/x-icon"},
                {".ics", "application/octet-stream"},
                {".idl", "text/plain"},
                {".ief", "image/ief"},
                {".iii", "application/x-iphone"},
                {".inc", "text/plain"},
                {".inf", "application/octet-stream"},
                {".ini", "text/plain"},
                {".inl", "text/plain"},
                {".ins", "application/x-internet-signup"},
                {".ipa", "application/x-itunes-ipa"},
                {".ipg", "application/x-itunes-ipg"},
                {".ipproj", "text/plain"},
                {".ipsw", "application/x-itunes-ipsw"},
                {".iqy", "text/x-ms-iqy"},
                {".isp", "application/x-internet-signup"},
                {".ite", "application/x-itunes-ite"},
                {".itlp", "application/x-itunes-itlp"},
                {".itms", "application/x-itunes-itms"},
                {".itpc", "application/x-itunes-itpc"},
                {".IVF", "video/x-ivf"},
                {".jar", "application/java-archive"},
                {".java", "application/octet-stream"},
                {".jck", "application/liquidmotion"},
                {".jcz", "application/liquidmotion"},
                {".jfif", "image/pjpeg"},
                {".jnlp", "application/x-java-jnlp-file"},
                {".jpb", "application/octet-stream"},
                {".jpe", "image/jpeg"},
                {".jpeg", "image/jpeg"},
                {".jpg", "image/jpeg"},
                {".js", "application/javascript"},
                {".json", "application/json"},
                {".jsx", "text/jscript"},
                {".jsxbin", "text/plain"},
                {".latex", "application/x-latex"},
                {".library-ms", "application/windows-library+xml"},
                {".lit", "application/x-ms-reader"},
                {".loadtest", "application/xml"},
                {".lpk", "application/octet-stream"},
                {".lsf", "video/x-la-asf"},
                {".lst", "text/plain"},
                {".lsx", "video/x-la-asf"},
                {".lzh", "application/octet-stream"},
                {".m13", "application/x-msmediaview"},
                {".m14", "application/x-msmediaview"},
                {".m1v", "video/mpeg"},
                {".m2t", "video/vnd.dlna.mpeg-tts"},
                {".m2ts", "video/vnd.dlna.mpeg-tts"},
                {".m2v", "video/mpeg"},
                {".m3u", "audio/x-mpegurl"},
                {".m3u8", "audio/x-mpegurl"},
                {".m4a", "audio/m4a"},
                {".m4b", "audio/m4b"},
                {".m4p", "audio/m4p"},
                {".m4r", "audio/x-m4r"},
                {".m4v", "video/x-m4v"},
                {".mac", "image/x-macpaint"},
                {".mak", "text/plain"},
                {".man", "application/x-troff-man"},
                {".manifest", "application/x-ms-manifest"},
                {".map", "text/plain"},
                {".master", "application/xml"},
                {".mda", "application/msaccess"},
                {".mdb", "application/x-msaccess"},
                {".mde", "application/msaccess"},
                {".mdp", "application/octet-stream"},
                {".me", "application/x-troff-me"},
                {".mfp", "application/x-shockwave-flash"},
                {".mht", "message/rfc822"},
                {".mhtml", "message/rfc822"},
                {".mid", "audio/mid"},
                {".midi", "audio/mid"},
                {".mix", "application/octet-stream"},
                {".mk", "text/plain"},
                {".mmf", "application/x-smaf"},
                {".mno", "text/xml"},
                {".mny", "application/x-msmoney"},
                {".mod", "video/mpeg"},
                {".mov", "video/quicktime"},
                {".movie", "video/x-sgi-movie"},
                {".mp2", "video/mpeg"},
                {".mp2v", "video/mpeg"},
                {".mp3", "audio/mpeg"},
                {".mp4", "video/mp4"},
                {".mp4v", "video/mp4"},
                {".mpa", "video/mpeg"},
                {".mpe", "video/mpeg"},
                {".mpeg", "video/mpeg"},
                {".mpf", "application/vnd.ms-mediapackage"},
                {".mpg", "video/mpeg"},
                {".mpp", "application/vnd.ms-project"},
                {".mpv2", "video/mpeg"},
                {".mqv", "video/quicktime"},
                {".ms", "application/x-troff-ms"},
                {".msi", "application/octet-stream"},
                {".mso", "application/octet-stream"},
                {".mts", "video/vnd.dlna.mpeg-tts"},
                {".mtx", "application/xml"},
                {".mvb", "application/x-msmediaview"},
                {".mvc", "application/x-miva-compiled"},
                {".mxp", "application/x-mmxp"},
                {".nc", "application/x-netcdf"},
                {".nsc", "video/x-ms-asf"},
                {".nws", "message/rfc822"},
                {".ocx", "application/octet-stream"},
                {".oda", "application/oda"},
                {".odb", "application/vnd.oasis.opendocument.database"},
                {".odc", "application/vnd.oasis.opendocument.chart"},
                {".odf", "application/vnd.oasis.opendocument.formula"},
                {".odg", "application/vnd.oasis.opendocument.graphics"},
                {".odh", "text/plain"},
                {".odi", "application/vnd.oasis.opendocument.image"},
                {".odl", "text/plain"},
                {".odm", "application/vnd.oasis.opendocument.text-master"},
                {".odp", "application/vnd.oasis.opendocument.presentation"},
                {".ods", "application/vnd.oasis.opendocument.spreadsheet"},
                {".odt", "application/vnd.oasis.opendocument.text"},
                {".oga", "audio/ogg"},
                {".ogg", "audio/ogg"},
                {".ogv", "video/ogg"},
                {".ogx", "application/ogg"},
                {".one", "application/onenote"},
                {".onea", "application/onenote"},
                {".onepkg", "application/onenote"},
                {".onetmp", "application/onenote"},
                {".onetoc", "application/onenote"},
                {".onetoc2", "application/onenote"},
                {".opus", "audio/ogg"},
                {".orderedtest", "application/xml"},
                {".osdx", "application/opensearchdescription+xml"},
                {".otf", "application/font-sfnt"},
                {".otg", "application/vnd.oasis.opendocument.graphics-template"},
                {".oth", "application/vnd.oasis.opendocument.text-web"},
                {".otp", "application/vnd.oasis.opendocument.presentation-template"},
                {".ots", "application/vnd.oasis.opendocument.spreadsheet-template"},
                {".ott", "application/vnd.oasis.opendocument.text-template"},
                {".oxt", "application/vnd.openofficeorg.extension"},
                {".p10", "application/pkcs10"},
                {".p12", "application/x-pkcs12"},
                {".p7b", "application/x-pkcs7-certificates"},
                {".p7c", "application/pkcs7-mime"},
                {".p7m", "application/pkcs7-mime"},
                {".p7r", "application/x-pkcs7-certreqresp"},
                {".p7s", "application/pkcs7-signature"},
                {".pbm", "image/x-portable-bitmap"},
                {".pcast", "application/x-podcast"},
                {".pct", "image/pict"},
                {".pcx", "application/octet-stream"},
                {".pcz", "application/octet-stream"},
                {".pdf", "application/pdf"},
                {".pfb", "application/octet-stream"},
                {".pfm", "application/octet-stream"},
                {".pfx", "application/x-pkcs12"},
                {".pgm", "image/x-portable-graymap"},
                {".pic", "image/pict"},
                {".pict", "image/pict"},
                {".pkgdef", "text/plain"},
                {".pkgundef", "text/plain"},
                {".pko", "application/vnd.ms-pki.pko"},
                {".pls", "audio/scpls"},
                {".pma", "application/x-perfmon"},
                {".pmc", "application/x-perfmon"},
                {".pml", "application/x-perfmon"},
                {".pmr", "application/x-perfmon"},
                {".pmw", "application/x-perfmon"},
                {".png", "image/png"},
                {".pnm", "image/x-portable-anymap"},
                {".pnt", "image/x-macpaint"},
                {".pntg", "image/x-macpaint"},
                {".pnz", "image/png"},
                {".pot", "application/vnd.ms-powerpoint"},
                {".potm", "application/vnd.ms-powerpoint.template.macroEnabled.12"},
                {".potx", "application/vnd.openxmlformats-officedocument.presentationml.template"},
                {".ppa", "application/vnd.ms-powerpoint"},
                {".ppam", "application/vnd.ms-powerpoint.addin.macroEnabled.12"},
                {".ppm", "image/x-portable-pixmap"},
                {".pps", "application/vnd.ms-powerpoint"},
                {".ppsm", "application/vnd.ms-powerpoint.slideshow.macroEnabled.12"},
                {".ppsx", "application/vnd.openxmlformats-officedocument.presentationml.slideshow"},
                {".ppt", "application/vnd.ms-powerpoint"},
                {".pptm", "application/vnd.ms-powerpoint.presentation.macroEnabled.12"},
                {".pptx", "application/vnd.openxmlformats-officedocument.presentationml.presentation"},
                {".prf", "application/pics-rules"},
                {".prm", "application/octet-stream"},
                {".prx", "application/octet-stream"},
                {".ps", "application/postscript"},
                {".psc1", "application/PowerShell"},
                {".psd", "application/octet-stream"},
                {".psess", "application/xml"},
                {".psm", "application/octet-stream"},
                {".psp", "application/octet-stream"},
                {".pub", "application/x-mspublisher"},
                {".pwz", "application/vnd.ms-powerpoint"},
                {".qht", "text/x-html-insertion"},
                {".qhtm", "text/x-html-insertion"},
                {".qt", "video/quicktime"},
                {".qti", "image/x-quicktime"},
                {".qtif", "image/x-quicktime"},
                {".qtl", "application/x-quicktimeplayer"},
                {".qxd", "application/octet-stream"},
                {".ra", "audio/x-pn-realaudio"},
                {".ram", "audio/x-pn-realaudio"},
                {".rar", "application/x-rar-compressed"},
                {".ras", "image/x-cmu-raster"},
                {".rat", "application/rat-file"},
                {".rc", "text/plain"},
                {".rc2", "text/plain"},
                {".rct", "text/plain"},
                {".rdlc", "application/xml"},
                {".reg", "text/plain"},
                {".resx", "application/xml"},
                {".rf", "image/vnd.rn-realflash"},
                {".rgb", "image/x-rgb"},
                {".rgs", "text/plain"},
                {".rm", "application/vnd.rn-realmedia"},
                {".rmi", "audio/mid"},
                {".rmp", "application/vnd.rn-rn_music_package"},
                {".roff", "application/x-troff"},
                {".rpm", "audio/x-pn-realaudio-plugin"},
                {".rqy", "text/x-ms-rqy"},
                {".rtf", "application/rtf"},
                {".rtx", "text/richtext"},
                {".ruleset", "application/xml"},
                {".s", "text/plain"},
                {".safariextz", "application/x-safari-safariextz"},
                {".scd", "application/x-msschedule"},
                {".scr", "text/plain"},
                {".sct", "text/scriptlet"},
                {".sd2", "audio/x-sd2"},
                {".sdp", "application/sdp"},
                {".sea", "application/octet-stream"},
                {".searchConnector-ms", "application/windows-search-connector+xml"},
                {".setpay", "application/set-payment-initiation"},
                {".setreg", "application/set-registration-initiation"},
                {".settings", "application/xml"},
                {".sgimb", "application/x-sgimb"},
                {".sgml", "text/sgml"},
                {".sh", "application/x-sh"},
                {".shar", "application/x-shar"},
                {".shtml", "text/html"},
                {".sit", "application/x-stuffit"},
                {".sitemap", "application/xml"},
                {".skin", "application/xml"},
                {".sldm", "application/vnd.ms-powerpoint.slide.macroEnabled.12"},
                {".sldx", "application/vnd.openxmlformats-officedocument.presentationml.slide"},
                {".slk", "application/vnd.ms-excel"},
                {".sln", "text/plain"},
                {".slupkg-ms", "application/x-ms-license"},
                {".smd", "audio/x-smd"},
                {".smi", "application/octet-stream"},
                {".smx", "audio/x-smd"},
                {".smz", "audio/x-smd"},
                {".snd", "audio/basic"},
                {".snippet", "application/xml"},
                {".snp", "application/octet-stream"},
                {".sol", "text/plain"},
                {".sor", "text/plain"},
                {".spc", "application/x-pkcs7-certificates"},
                {".spl", "application/futuresplash"},
                {".spx", "audio/ogg"},
                {".src", "application/x-wais-source"},
                {".srf", "text/plain"},
                {".SSISDeploymentManifest", "text/xml"},
                {".ssm", "application/streamingmedia"},
                {".sst", "application/vnd.ms-pki.certstore"},
                {".stl", "application/vnd.ms-pki.stl"},
                {".sv4cpio", "application/x-sv4cpio"},
                {".sv4crc", "application/x-sv4crc"},
                {".svc", "application/xml"},
                {".svg", "image/svg+xml"},
                {".swf", "application/x-shockwave-flash"},
                {".step", "application/step"},
                {".stp", "application/step"},
                {".t", "application/x-troff"},
                {".tar", "application/x-tar"},
                {".tcl", "application/x-tcl"},
                {".testrunconfig", "application/xml"},
                {".testsettings", "application/xml"},
                {".tex", "application/x-tex"},
                {".texi", "application/x-texinfo"},
                {".texinfo", "application/x-texinfo"},
                {".tgz", "application/x-compressed"},
                {".thmx", "application/vnd.ms-officetheme"},
                {".thn", "application/octet-stream"},
                {".tif", "image/tiff"},
                {".tiff", "image/tiff"},
                {".tlh", "text/plain"},
                {".tli", "text/plain"},
                {".toc", "application/octet-stream"},
                {".tr", "application/x-troff"},
                {".trm", "application/x-msterminal"},
                {".trx", "application/xml"},
                {".ts", "video/vnd.dlna.mpeg-tts"},
                {".tsv", "text/tab-separated-values"},
                {".ttf", "application/font-sfnt"},
                {".tts", "video/vnd.dlna.mpeg-tts"},
                {".txt", "text/plain"},
                {".u32", "application/octet-stream"},
                {".uls", "text/iuls"},
                {".user", "text/plain"},
                {".ustar", "application/x-ustar"},
                {".vb", "text/plain"},
                {".vbdproj", "text/plain"},
                {".vbk", "video/mpeg"},
                {".vbproj", "text/plain"},
                {".vbs", "text/vbscript"},
                {".vcf", "text/x-vcard"},
                {".vcproj", "application/xml"},
                {".vcs", "text/plain"},
                {".vcxproj", "application/xml"},
                {".vddproj", "text/plain"},
                {".vdp", "text/plain"},
                {".vdproj", "text/plain"},
                {".vdx", "application/vnd.ms-visio.viewer"},
                {".vml", "text/xml"},
                {".vscontent", "application/xml"},
                {".vsct", "text/xml"},
                {".vsd", "application/vnd.visio"},
                {".vsi", "application/ms-vsi"},
                {".vsix", "application/vsix"},
                {".vsixlangpack", "text/xml"},
                {".vsixmanifest", "text/xml"},
                {".vsmdi", "application/xml"},
                {".vspscc", "text/plain"},
                {".vss", "application/vnd.visio"},
                {".vsscc", "text/plain"},
                {".vssettings", "text/xml"},
                {".vssscc", "text/plain"},
                {".vst", "application/vnd.visio"},
                {".vstemplate", "text/xml"},
                {".vsto", "application/x-ms-vsto"},
                {".vsw", "application/vnd.visio"},
                {".vsx", "application/vnd.visio"},
                {".vtx", "application/vnd.visio"},
                {".wav", "audio/wav"},
                {".wave", "audio/wav"},
                {".wax", "audio/x-ms-wax"},
                {".wbk", "application/msword"},
                {".wbmp", "image/vnd.wap.wbmp"},
                {".wcm", "application/vnd.ms-works"},
                {".wdb", "application/vnd.ms-works"},
                {".wdp", "image/vnd.ms-photo"},
                {".webarchive", "application/x-safari-webarchive"},
                {".webm", "video/webm"},
                {".webp", "image/webp"}, /* https://en.wikipedia.org/wiki/WebP */
                {".webtest", "application/xml"},
                {".wiq", "application/xml"},
                {".wiz", "application/msword"},
                {".wks", "application/vnd.ms-works"},
                {".WLMP", "application/wlmoviemaker"},
                {".wlpginstall", "application/x-wlpg-detect"},
                {".wlpginstall3", "application/x-wlpg3-detect"},
                {".wm", "video/x-ms-wm"},
                {".wma", "audio/x-ms-wma"},
                {".wmd", "application/x-ms-wmd"},
                {".wmf", "application/x-msmetafile"},
                {".wml", "text/vnd.wap.wml"},
                {".wmlc", "application/vnd.wap.wmlc"},
                {".wmls", "text/vnd.wap.wmlscript"},
                {".wmlsc", "application/vnd.wap.wmlscriptc"},
                {".wmp", "video/x-ms-wmp"},
                {".wmv", "video/x-ms-wmv"},
                {".wmx", "video/x-ms-wmx"},
                {".wmz", "application/x-ms-wmz"},
                {".woff", "application/font-woff"},
                {".wpl", "application/vnd.ms-wpl"},
                {".wps", "application/vnd.ms-works"},
                {".wri", "application/x-mswrite"},
                {".wrl", "x-world/x-vrml"},
                {".wrz", "x-world/x-vrml"},
                {".wsc", "text/scriptlet"},
                {".wsdl", "text/xml"},
                {".wvx", "video/x-ms-wvx"},
                {".x", "application/directx"},
                {".xaf", "x-world/x-vrml"},
                {".xaml", "application/xaml+xml"},
                {".xap", "application/x-silverlight-app"},
                {".xbap", "application/x-ms-xbap"},
                {".xbm", "image/x-xbitmap"},
                {".xdr", "text/plain"},
                {".xht", "application/xhtml+xml"},
                {".xhtml", "application/xhtml+xml"},
                {".xla", "application/vnd.ms-excel"},
                {".xlam", "application/vnd.ms-excel.addin.macroEnabled.12"},
                {".xlc", "application/vnd.ms-excel"},
                {".xld", "application/vnd.ms-excel"},
                {".xlk", "application/vnd.ms-excel"},
                {".xll", "application/vnd.ms-excel"},
                {".xlm", "application/vnd.ms-excel"},
                {".xls", "application/vnd.ms-excel"},
                {".xlsb", "application/vnd.ms-excel.sheet.binary.macroEnabled.12"},
                {".xlsm", "application/vnd.ms-excel.sheet.macroEnabled.12"},
                {".xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"},
                {".xlt", "application/vnd.ms-excel"},
                {".xltm", "application/vnd.ms-excel.template.macroEnabled.12"},
                {".xltx", "application/vnd.openxmlformats-officedocument.spreadsheetml.template"},
                {".xlw", "application/vnd.ms-excel"},
                {".xml", "text/xml"},
                {".xmta", "application/xml"},
                {".xof", "x-world/x-vrml"},
                {".XOML", "text/plain"},
                {".xpm", "image/x-xpixmap"},
                {".xps", "application/vnd.ms-xpsdocument"},
                {".xrm-ms", "text/xml"},
                {".xsc", "application/xml"},
                {".xsd", "text/xml"},
                {".xsf", "text/xml"},
                {".xsl", "text/xml"},
                {".xslt", "text/xml"},
                {".xsn", "application/octet-stream"},
                {".xss", "application/xml"},
                {".xspf", "application/xspf+xml"},
                {".xtp", "application/octet-stream"},
                {".xwd", "image/x-xwindowdump"},
                {".z", "application/x-compress"},
                {".zip", "application/zip"},

                {"application/fsharp-script", ".fsx"},
                {"application/msaccess", ".adp"},
                {"application/msword", ".doc"},
                {"application/octet-stream", ".bin"},
                {"application/onenote", ".one"},
                {"application/postscript", ".eps"},
                {"application/step", ".step"},
                {"application/vnd.ms-excel", ".xls"},
                {"application/vnd.ms-powerpoint", ".ppt"},
                {"application/vnd.ms-works", ".wks"},
                {"application/vnd.visio", ".vsd"},
                {"application/x-director", ".dir"},
                {"application/x-shockwave-flash", ".swf"},
                {"application/x-x509-ca-cert", ".cer"},
                {"application/x-zip-compressed", ".zip"},
                {"application/xhtml+xml", ".xhtml"},
                {"application/xml", ".xml"},  // anomoly, .xml -> text/xml, but application/xml -> many thingss, but all are xml, so safest is .xml
                {"audio/aac", ".AAC"},
                {"audio/aiff", ".aiff"},
                {"audio/basic", ".snd"},
                {"audio/mid", ".midi"},
                {"audio/wav", ".wav"},
                {"audio/x-m4a", ".m4a"},
                {"audio/x-mpegurl", ".m3u"},
                {"audio/x-pn-realaudio", ".ra"},
                {"audio/x-smd", ".smd"},
                {"image/bmp", ".bmp"},
                {"image/jpeg", ".jpg"},
                {"image/pict", ".pic"},
                {"image/png", ".png"},
                {"image/tiff", ".tiff"},
                {"image/x-macpaint", ".mac"},
                {"image/x-quicktime", ".qti"},
                {"message/rfc822", ".eml"},
                {"text/html", ".html"},
                {"text/plain", ".txt"},
                {"text/scriptlet", ".wsc"},
                {"text/xml", ".xml"},
                {"video/3gpp", ".3gp"},
                {"video/3gpp2", ".3gp2"},
                {"video/mp4", ".mp4"},
                {"video/mpeg", ".mpg"},
                {"video/quicktime", ".mov"},
                {"video/vnd.dlna.mpeg-tts", ".m2t"},
                {"video/x-dv", ".dv"},
                {"video/x-la-asf", ".lsf"},
                {"video/x-ms-asf", ".asf"},
                {"x-world/x-vrml", ".xof"},
                #endregion
                };
            var cache = mappings.ToList(); // need ToList() to avoid modifying while still enumerating

            foreach (var mapping in cache)
            {
                if (!mappings.ContainsKey(mapping.Value))
                {
                    mappings.Add(mapping.Value, mapping.Key);
                }
            }
            return mappings;
        }

        public string GetMimeType(string extension)
        {
            if (extension == null)
            {
                throw new ArgumentNullException("extension");
            }
            if (!extension.StartsWith("."))
            {
                extension = "." + extension;
            }
            string mime;
            return _mappings.Value.TryGetValue(extension, out mime) ? mime : "application/octet-stream";
        }

        public string GetExtension(string mimeType)
        {
            if (mimeType == null)
            {
                throw new ArgumentNullException("mimeType");
            }
            if (mimeType.StartsWith("."))
            {
                throw new ArgumentException("Requested mime type is not valid: " + mimeType);
            }
            string extension;
            if (_mappings.Value.TryGetValue(mimeType, out extension))
            {
                return extension;
            }
            throw new ArgumentException("Requested mime type is not registered: " + mimeType);
        }
    }

    public class IconType
    {
        private static readonly Lazy<IDictionary<string, string>> _mappings = new Lazy<IDictionary<string, string>>(BuildMappings);

        private static IDictionary<string, string> BuildMappings()
        {
            var mappings = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase) {

                #region Big freaking list of mime types
                // extension -> icon font awesone
                //   and
                // icon font awesone -> extension

                {".323", "far fa-file-alt"},
                {".3g2", "far fa-file-video"},
                {".3gp", "far fa-file-video"},
                {".3gp2", "far fa-file-video"},
                {".3gpp", "far fa-file-video"},
                {".7z", "far fa-file-archive"},
                {".aa", "far fa-file-audio"},
                {".AAC", "far fa-file-audio"},                
                {".aax", "far fa-file-audio"},
                {".ac3", "far fa-file-audio"},                
                {".AddIn", "far fa-file-alt"},                
                {".ADT", "far fa-file-audio"},
                {".ADTS", "far fa-file-audio"},                
                {".aif", "far fa-file-audio"},
                {".aifc", "far fa-file-audio"},
                {".aiff", "far fa-file-audio"},                
                {".apk", "far fa-file-archive" },
                {".application", "far fa-file-code"},
                {".art", "far fa-file-image"},
                {".asa", "far fa-file-code"},
                {".asax", "far fa-file-code"},
                {".ascx", "far fa-file-code"},
                {".asd", "far fa-file-code"},
                {".asf", "far fa-file-video"},
                {".ashx", "far fa-file-code"},
                {".asi", "far fa-file-code"},
                {".asm", "far fa-file-alt"},
                {".asmx", "far fa-file-code"},
                {".asp", "far fa-file-code"},
                {".aspx", "far fa-file-code"},
                {".asr", "far fa-file-video"},
                {".asx", "far fa-file-video"},
                {".atom", "far fa-file-code"},
                {".au", "far fa-file-audio"},
                {".avi", "far fa-file-video"},
                {".axa", "far fa-file-audio"},
                {".axs", "far fa-file-code"},
                {".axv", "far fa-file-video"},
                {".bas", "far fa-file-alt"},
                {".bcpio", "far fa-file-code"},
                {".bin", "far fa-file-code"},
                {".bmp", "far fa-file-image"},
                {".c", "far fa-file-alt"},
                {".cab", "far fa-file-code"},
                {".caf", "far fa-file-audio"},  
                {".cc", "far fa-file-alt"},
                {".cd", "far fa-file-alt"},
                {".cdda", "far fa-file-audio"},  
                {".cfg", "far fa-file-alt"},
                {".class", "far fa-file-code"},
                {".cmd", "far fa-file-alt"},
                {".cmx", "far fa-file-image"},
                {".cnf", "far fa-file-alt"},
                {".cod", "far fa-file-image"},
                {".config", "far fa-file-alt"},
                {".contact", "fa-id-badge"},
                {".coverage", "far fa-file-code"},
                {".cpp", "far fa-file-alt"},
                {".cs", "far fa-file-alt"},
                {".csdproj", "far fa-file-alt"},                
                {".csproj", "far fa-file-alt"},
                {".css", "far fa-file-code"},
                {".csv", "far fa-file-csv"},                
                {".cxx", "far fa-file-alt"},                
                {".datasource", "far fa-file-code"},
                {".dbproj", "far fa-file-alt"},                
                {".def", "far fa-file-alt"},
                {".dgml", "far fa-file-code"},
                {".dib", "far fa-file-image"},
                {".dif", "far fa-file-video"},                
                {".disco", "far fa-file-code"},
                {".divx", "far fa-file-video"},
                {".dll", "far fa-file-code"},
                {".dll.config", "far fa-file-code"},                
                {".doc", "far fa-file-word"},
                {".docm", "far fa-file-word"},
                {".docx", "far fa-file-word"},
                {".dot", "far fa-file-word"},
                {".dotm", "far fa-file-word"},
                {".dotx", "far fa-file-word"},                
                {".dsw", "far fa-file-alt"},
                {".dtd", "far fa-file-code"},
                {".dtsConfig", "far fa-file-code"},
                {".dv", "far fa-file-video"},                
                {".exe", "far fa-file-code"},
                {".exe.config", "far fa-file-code"},
                {".filters", "far fa-file-code"},
                {".flac", "far fa-file-audio"},
                {".flv", "far fa-file-video"},
                {".fsscript", "far fa-file-code"},
                {".fsx", "far fa-file-code"},
                {".generictest", "far fa-file-code"},
                {".gif", "far fa-file-image"},
                {".gpx", "far fa-file-code"},
                {".gsm", "far fa-file-audio"},
                {".h", "far fa-file-alt"},                
                {".hpp", "far fa-file-alt"},                
                {".htm", "far fa-file-code"},
                {".html", "far fa-file-code"},
                {".htt", "far fa-file-code"},
                {".hxa", "far fa-file-code"},
                {".hxc", "far fa-file-code"},                
                {".hxe", "far fa-file-code"},
                {".hxf", "far fa-file-code"},                
                {".hxk", "far fa-file-code"},                
                {".hxt", "far fa-file-code"},
                {".hxv", "far fa-file-code"},                
                {".hxx", "far fa-file-alt"},
                {".i", "far fa-file-alt"},
                {".ico", "far fa-file-image"},                
                {".idl", "far fa-file-alt"},
                {".ief", "far fa-file-image"},                
                {".inc", "far fa-file-alt"},                
                {".ini", "far fa-file-alt"},
                {".inl", "far fa-file-alt"},
                {".ipproj", "far fa-file-alt"},                
                {".IVF", "far fa-file-video"},
                {".jar", "far fa-file-archive"},
                {".java", "far fa-file-code"},
                {".jck", "far fa-file-code"},
                {".jcz", "far fa-file-code"},
                {".jfif", "far fa-file-image"},
                {".jnlp", "far fa-file-code"},
                {".jpb", "far fa-file-code"},
                {".jpe", "far fa-file-image"},
                {".jpeg", "far fa-file-image"},
                {".jpg", "far fa-file-image"},
                {".js", "far fa-file-code"},
                {".json", "far fa-file-code"},
                {".jsx", "far fa-file-code"},
                {".jsxbin", "far fa-file-alt"},
                {".latex", "far fa-file-code"},
                {".library-ms", "far fa-file-code"},
                {".lit", "far fa-file-code"},
                {".loadtest", "far fa-file-code"},                
                {".lsf", "far fa-file-video"},
                {".lst", "far fa-file-alt"},
                {".lsx", "far fa-file-video"},                
                {".m1v", "far fa-file-video"},
                {".m2t", "far fa-file-video"},
                {".m2ts", "far fa-file-video"},
                {".m2v", "far fa-file-video"},
                {".m3u", "far fa-file-audio"},
                {".m3u8", "far fa-file-audio"},
                {".m4a", "far fa-file-audio"},
                {".m4b", "far fa-file-audio"},
                {".m4p", "far fa-file-audio"},
                {".m4r", "far fa-file-audio"},
                {".m4v", "far fa-file-video"},
                {".mac", "far fa-file-image"},
                {".mak", "far fa-file-alt"},
                {".map", "far fa-file-alt"},
                {".master", "far fa-file-code"},
                {".mda", "fas fa-database"},
                {".mdb", "fas fa-database"},
                {".mde", "fas fa-database"},
                {".mdp", "fas fa-database"},
                {".mid", "far fa-file-audio"},
                {".midi", "far fa-file-audio"},                
                {".mk", "far fa-file-alt"},                
                {".mno", "far fa-file-code"},                
                {".mod", "far fa-file-video"},
                {".mov", "far fa-file-video"},
                {".movie", "far fa-file-video"},
                {".mp2", "far fa-file-video"},
                {".mp2v", "far fa-file-video"},
                {".mp3", "far fa-file-audio"},
                {".mp4", "far fa-file-video"},
                {".mp4v", "far fa-file-video"},
                {".mpa", "far fa-file-video"},
                {".mpe", "far fa-file-video"},
                {".mpeg", "far fa-file-video"},                
                {".mpg", "far fa-file-video"},                
                {".mpv2", "far fa-file-video"},
                {".mqv", "far fa-file-video"},                
                {".mts", "far fa-file-video"},
                {".mtx", "far fa-file-code"},                
                {".nsc", "far fa-file-video"},                
                {".odh", "far fa-file-alt"},
                {".odi", "far fa-file-image"},
                {".odl", "far fa-file-alt"},                
                {".oga", "far fa-file-audio"},
                {".ogg", "far fa-file-audio"},
                {".ogv", "far fa-file-video"},           
                {".opus", "far fa-file-audio"},
                {".orderedtest", "far fa-file-code"},                
                {".pbm", "far fa-file-image"},                
                {".pct", "far fa-file-image"},                
                {".pdf", "far fa-file-pdf"},                
                {".pgm", "far fa-file-image"},
                {".pic", "far fa-file-image"},
                {".pict", "far fa-file-image"},
                {".pkgdef", "far fa-file-alt"},
                {".pkgundef", "far fa-file-alt"},                
                {".pls", "far fa-file-audio"},                
                {".png", "far fa-file-image"},
                {".pnm", "far fa-file-image"},
                {".pnt", "far fa-file-image"},
                {".pntg", "far fa-file-image"},
                {".pnz", "far fa-file-image"},
                {".pot", "far fa-file-powerpoint"},
                {".potm", "far fa-file-powerpoint"},
                {".potx", "far fa-file-powerpoint"},
                {".ppa", "far fa-file-powerpoint"},
                {".ppam", "far fa-file-powerpoint"},
                {".ppm", "far fa-file-image"},
                {".pps", "far fa-file-powerpoint"},
                {".ppsm", "far fa-file-powerpoint"},
                {".ppsx", "far fa-file-powerpoint"},
                {".ppt", "far fa-file-powerpoint"},
                {".pptm", "far fa-file-powerpoint"},
                {".pptx", "far fa-file-powerpoint"},
                {".psess", "far fa-file-code"},
                {".pwz", "far fa-file-powerpoint"},
                {".qht", "far fa-file-code"},
                {".qhtm", "far fa-file-code"},
                {".qt", "far fa-file-video"},
                {".qti", "far fa-file-image"},
                {".qtif", "far fa-file-image"},
                {".ra", "far fa-file-audio"},
                {".ram", "far fa-file-audio"},
                {".rar", "far fa-file-archive"},
                {".ras", "far fa-file-image"},
                {".rat", "far fa-file-archive"},
                {".rc", "far fa-file-alt"},
                {".rc2", "far fa-file-alt"},
                {".rct", "far fa-file-alt"},
                {".rdlc", "far fa-file-code"},
                {".reg", "far fa-file-alt"},
                {".resx", "far fa-file-code"},
                {".rf", "far fa-file-image"},
                {".rgb", "far fa-file-image"},
                {".rgs", "far fa-file-alt"},
                {".rmi", "far fa-file-audio"},
                {".rpm", "far fa-file-audio"},
                {".ruleset", "far fa-file-code"},
                {".s", "far fa-file-alt"},
                {".scr", "far fa-file-alt"},
                {".sd2", "far fa-file-audio"},
                {".settings", "far fa-file-code"},
                {".shtml", "far fa-file-code"},
                {".sitemap", "far fa-file-code"},
                {".skin", "far fa-file-code"},
                {".sldm", "far fa-file-powerpoint"},
                {".sldx", "far fa-file-powerpoint"},
                {".slk", "far fa-file-excel"},
                {".sln", "far fa-file-alt"},
                {".smd", "far fa-file-audio"},
                {".smx", "far fa-file-audio"},
                {".smz", "far fa-file-audio"},
                {".snd", "far fa-file-audio"},
                {".snippet", "far fa-file-code"},
                {".sol", "far fa-file-alt"},
                {".sor", "far fa-file-alt"},
                {".spx", "far fa-file-audio"},
                {".src", "far fa-file-archive"},
                {".srf", "far fa-file-alt"},
                {".SSISDeploymentManifest", "far fa-file-code"},
                {".svc", "far fa-file-code"},
                {".svg", "far fa-file-image"},
                {".testrunconfig", "far fa-file-code"},
                {".testsettings", "far fa-file-code"},
                {".tif", "far fa-file-image"},
                {".tiff", "far fa-file-image"},
                {".tlh", "far fa-file-alt"},
                {".tli", "far fa-file-alt"},
                {".trx", "far fa-file-code"},
                {".ts", "far fa-file-video"},
                {".tts", "far fa-file-video"},
                {".txt", "far fa-file-alt"},
                {".user", "far fa-file-alt"},
                {".vb", "far fa-file-alt"},
                {".vbdproj", "far fa-file-alt"},
                {".vbk", "far fa-file-video"},
                {".vbproj", "far fa-file-alt"},
                {".vcproj", "far fa-file-code"},
                {".vcs", "far fa-file-alt"},
                {".vcxproj", "far fa-file-code"},
                {".vddproj", "far fa-file-alt"},
                {".vdp", "far fa-file-alt"},
                {".vdproj", "far fa-file-alt"},
                {".vml", "far fa-file-code"},
                {".vscontent", "far fa-file-code"},
                {".vsct", "far fa-file-code"},
                {".vsixlangpack", "far fa-file-code"},
                {".vsixmanifest", "far fa-file-code"},
                {".vsmdi", "far fa-file-code"},
                {".vspscc", "far fa-file-alt"},
                {".vsscc", "far fa-file-alt"},
                {".vssettings", "far fa-file-code"},
                {".vssscc", "far fa-file-alt"},
                {".vstemplate", "far fa-file-code"},
                {".wav", "far fa-file-audio"},
                {".wave", "far fa-file-audio"},
                {".wax", "far fa-file-audio"},
                {".wbk", "far fa-file-word"},
                {".wbmp", "far fa-file-image"},
                {".wdp", "far fa-file-image"},
                {".webm", "far fa-file-video"},
                {".webp", "far fa-file-image"}, /* https://en.wikipedia.org/wiki/WebP */
                {".webtest", "far fa-file-code"},
                {".wiq", "far fa-file-code"},
                {".wm", "far fa-file-video"},
                {".wma", "far fa-file-audio"},
                {".wmp", "far fa-file-video"},
                {".wmv", "far fa-file-video"},
                {".wmx", "far fa-file-video"},
                {".wsdl", "far fa-file-code"},
                {".wvx", "far fa-file-video"},
                {".xbm", "far fa-file-image"},
                {".xdr", "far fa-file-alt"},
                {".xht", "far fa-file-code"},
                {".xhtml", "far fa-file-code"},
                {".xla", "far fa-file-excel"},
                {".xlam", "far fa-file-excel"},
                {".xlc", "far fa-file-excel"},
                {".xld", "far fa-file-excel"},
                {".xlk", "far fa-file-excel"},
                {".xll", "far fa-file-excel"},
                {".xlm", "far fa-file-excel"},
                {".xls", "far fa-file-excel"},
                {".xlsb", "far fa-file-excel"},
                {".xlsm", "far fa-file-excel"},
                {".xlsx", "far fa-file-excel"},
                {".xlt", "far fa-file-excel"},
                {".xltm", "far fa-file-excel"},
                {".xltx", "far fa-file-excel"},
                {".xlw", "far fa-file-excel"},
                {".xml", "far fa-file-code"},
                {".xmta", "far fa-file-code"},
                {".XOML", "far fa-file-alt"},
                {".xpm", "far fa-file-image"},
                {".xrm-ms", "far fa-file-code"},
                {".xsc", "far fa-file-code"},
                {".xsd", "far fa-file-code"},
                {".xsf", "far fa-file-code"},
                {".xsl", "far fa-file-code"},
                {".xslt", "far fa-file-code"},
                {".xss", "far fa-file-code"},
                {".xwd", "far fa-file-image"},
                {".z", "far fa-file-archive"},
                {".zip", "far fa-file-archive"},

                {"application/fsharp-script", "far fa-file-code"},
                {"application/msaccess", "fas fa-database"},
                {"application/msword", "far fa-file-word"},
                {"application/octet-stream", "far fa-file-archive"},
                {"application/vnd.ms-excel", "far fa-file-excel"},
                {"application/vnd.ms-powerpoint", "far fa-file-powerpoint"},
                {"application/x-zip-compressed", "far fa-file-archive"},
                {"application/xhtml+xml", "far fa-file-code"},
                {"application/xml", "far fa-file-code"},  // anomoly, .xml -> text/xml, but application/xml -> many thingss, but all are xml, so safest is .xml
                {"audio/aac", "far fa-file-audio"},
                {"audio/aiff", "far fa-file-audio"},
                {"audio/basic", "far fa-file-audio"},
                {"audio/mid", "far fa-file-audio"},
                {"audio/wav", "far fa-file-audio"},
                {"audio/x-m4a", "far fa-file-audio"},
                {"audio/x-mpegurl", "far fa-file-audio"},
                {"audio/x-pn-realaudio", "far fa-file-audio"},
                {"audio/x-smd", "far fa-file-audio"},
                {"image/bmp", "far fa-file-image"},
                {"image/jpeg", "far fa-file-image"},
                {"image/pict", "far fa-file-image"},
                {"image/png", "far fa-file-image"},
                {"image/tiff", "far fa-file-image"},
                {"image/x-macpaint", "far fa-file-image"},
                {"image/x-quicktime", "far fa-file-image"},
                {"message/rfc822", "far fa-file-code"},
                {"text/html", "far fa-file-code"},
                {"text/plain", "far fa-file-code"},
                {"text/scriptlet", "far fa-file-code"},
                {"text/xml", "far fa-file-code"},
                {"video/3gpp", "far fa-file-video"},
                {"video/3gpp2", "far fa-file-video"},
                {"video/mp4", "far fa-file-video"},
                {"video/mpeg", "far fa-file-video"},
                {"video/quicktime", "far fa-file-video"},
                {"video/vnd.dlna.mpeg-tts", "far fa-file-video"},
                {"video/x-dv", "far fa-file-video"},
                {"video/x-la-asf", "far fa-file-video"},
                {"video/x-ms-asf", "far fa-file-video"},
                #endregion
                };
            var cache = mappings.ToList(); // need ToList() to avoid modifying while still enumerating

            foreach (var mapping in cache)
            {
                if (!mappings.ContainsKey(mapping.Value))
                {
                    mappings.Add(mapping.Value, mapping.Key);
                }
            }
            return mappings;
        }

        public string GetIconType(string extension)
        {
            if (extension == null)
            {
                throw new ArgumentNullException("extension");
            }
            if (!extension.StartsWith("."))
            {
                extension = "." + extension;
            }
            string mime;
            return _mappings.Value.TryGetValue(extension, out mime) ? mime : "far fa-file";
        }
    }
}